# Generated by Django 4.0.3 on 2025-04-24 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0002_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(default='default_room', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_chat_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
