# Generated by Django 4.0.3 on 2025-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_joincourselist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_student',
            name='grade',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Not Graded', 'Not Graded'), ('Satisfactory', 'Satisfactory'), ('Good', 'Good'), ('Merit', 'Merit'), ('ممتاز', 'ممتاز')], default='Not Submitted', max_length=200),
        ),
    ]
